### ISSUE TITLE
Submit issues

### ISSUE THREAD

**Issue by ghost** [felixarntz/bootstrap-for-contact-form-7#46]
1. The default stylesheet is unqueued; this prevents the loading indicator from working.

   This snippet needs to be reattached.
```css
div.wpcf7 .ajax-loader.is-active {
    visibility: visible;
}
div.wpcf7 .ajax-loader {
    visibility: hidden;
    display: inline-block;
    background-image: url(/wp-content/plugins/contact-form-7/images/ajax-loader.gif);
    width: 16px;
    height: 16px;
    border: none;
    padding: 0;
    margin: 0 0 0 4px;
    vertical-align: middle;
}
```

2. The form is never reset after submitting with validation errors. `is-active` will stay on the AJAX loader.

3. The submit button will never be disabled while sending. We have a lot of users sending from mobile devices and currently end up with either lots of duplicates or errors due to recaptcha only passing once.
